var mappings = {
	'bicho do mato': 'bicho-do-mato',
	'boioçuboias': 'boioçubóias',
	'beltrano': 'Beltrano',
	'batizees': 'baptizees',
	'bico de pato': 'bico-de-pato',
	'beltrana': 'Beltrana',
	'birreator': 'birreactor',
	'bicho do mata': 'bicho-do-mata',
	'batizásseies': 'baptizásseies',
	'bubonoide': 'bubonóide',
	'bicos-de-pato': 'b',
	'batistas': 'baptistas',
	'batizaríeis': 'baptizaríeis',
	'bissetoras': 'bissectoras',
	'batizarão': 'baptizarão',
	'benzoica': 'benzóica',
	'bioeletricidade': 'bioelectricidade',
	'bálsamo do Canadá': 'bálsamo-do-canadá',
	'batizásseis': 'baptizásseis',
	'benzoico': 'benzóico',
	'batizamentas': 'baptizamentas',
	'bálsamos-do-Canadá': 'bálsamos-do-canadá',
	'balsamoides': 'balsamóides',
	'biobjetividades': 'biobjectividades',
	'bissoide': 'bissóide',
	'belonoide': 'belonóide',
	'beroide': 'beróide',
	'batizaras': 'baptizaras',
	'batizens': 'baptizens',
	'baba de moça': 'baba-de-moça',
	'batistérios': 'baptistérios',
	'babas-de-camelo': 'b',
	'barotáticos': 'barotácticos',
	'boca de siri': 'boca-de-siri',
	'batizáramoes': 'baptizáramoes',
	'batizarem': 'baptizarem',
	'batizaram': 'baptizaram',
	'barriga de bicho': 'barriga-de-bicho',
	'bilhete de identidade': 'bilhete-de-identidade',
	'barriga de bicha': 'barriga-de-bicha',
	'braquipinacoide': 'braquipinacóide',
	'batizamenta': 'baptizamenta',
	'boca de sina': 'boca-de-sina',
	'bichas-de-rabear': 'b',
	'boca de sino': 'boca-de-sino',
	'batizamento': 'baptizamento',
	'bico de pata': 'bico-de-pata',
	'bichos-de-sete-cabeças': 'b',
	'bioelétricos': 'bioeléctricos',
	'birrefrações': 'birrefracções',
	'birrefração': 'birrefracção',
	'belemnoide': 'belemnóide',
	'biobjetivos': 'biobjectivos',
	'batizareies': 'baptizareies',
	'barca de ouro': 'barca-de-ouro',
	'batizo': 'baptizo',
	'batizados': 'baptizados',
	'batizáreis': 'baptizáreis',
	'barca de oura': 'barca-de-oura',
	'batiza': 'baptiza',
	'batizastes': 'baptizastes',
	'batize': 'baptize',
	'bioatividade': 'bioactividade',
	'barbas-de-baleia': 'b',
	'barriga de freira': 'barriga-de-freira',
	'bioeletricidades': 'bioelectricidades',
	'braço de armas': 'braço-de-armas',
	'balsamoide': 'balsamóide',
	'batizou': 'baptizou',
	'branco de baleia': 'branco-de-baleia',
	'batizardes': 'baptizardes',
	'braquicataletas': 'braquicatalectas',
	'belonoides': 'belonóides',
	'batizandas': 'baptizandas',
	'bico de mocha': 'bico-de-mocha',
	'bota de elástico': 'bota-de-elástico',
	'bubonoides': 'bubonóides',
	'bife de caneca': 'bife-de-caneca',
	'bissetora': 'bissectora',
	'braquipinacoides': 'braquipinacóides',
	'bico de gás': 'bico-de-gás',
	'batizara': 'baptizara',
	'beroides': 'beróides',
	'batizarians': 'baptizarians',
	'botrioide': 'botrióide',
	'braquicataleta': 'braquicatalecta',
	'bissetor': 'bissector',
	'batizaies': 'baptizaies',
	'beltranos': 'Beltranos',
	'batistéria': 'baptistéria',
	'bioativos': 'bioactivos',
	'balão de ensaio': 'balão-de-ensaio',
	'biobjetivas': 'biobjectivas',
	'bioflavonoides': 'bioflavonóides',
	'batizeis': 'baptizeis',
	'barba de baleia': 'barba-de-baleia',
	'benzoicas': 'benzóicas',
	'batizaríamos': 'baptizaríamos',
	'balanoides': 'balanóides',
	'bronquetático': 'bronquectático',
	'batizadas': 'baptizadas',
	'batizavas': 'baptizavas',
	'batizássemos': 'baptizássemos',
	'bico de gaviâ': 'bico-de-gaviâ',
	'batracoide': 'batracóide',
	'bioelétricas': 'bioeléctricas',
	'braço de ferro': 'braço-de-ferro',
	'braço de ferra': 'braço-de-ferra',
	'bicos-de-obra': 'b',
	'bichas-de-sete-cabeças': 'b',
	'bom de bica': 'bom-de-bica',
	'birreatora': 'birreactora',
	'batizáveis': 'baptizáveis',
	'bairro de lata': 'bairro-de-lata',
	'bom de bico': 'bom-de-bico',
	'batizoa': 'baptizoa',
	'bico de mocho': 'bico-de-mocho',
	'braquicataléticos': 'braquicatalécticos',
	'bicho do buraca': 'bicho-do-buraca',
	'bicho do buraco': 'bicho-do-buraco',
	'basipinacoides': 'basipinacóides',
	'bronquetáticos': 'bronquectáticos',
	'batizos': 'baptizos',
	'batizasse': 'baptizasse',
	'braquicataletos': 'braquicatalectos',
	'bicho do ouvido': 'bicho-do-ouvido',
	'bicho do ouvida': 'bicho-do-ouvida',
	'batizareis': 'baptizareis',
	'batizariam': 'baptizariam',
	'batizandos': 'baptizandos',
	'batizarias': 'baptizarias',
	'bioativas': 'bioactivas',
	'batizavam': 'baptizavam',
	'bicha de rabear': 'bicha-de-rabear',
	'batizáramos': 'baptizáramos',
	'beijo de moça': 'beijo-de-moça',
	'batizei': 'baptizei',
	'boca de incêndio': 'boca-de-incêndio',
	'braquioide': 'braquióide',
	'biocoloide': 'biocolóide',
	'batizanda': 'baptizanda',
	'bilhetes-de-visita': 'b',
	'batizava': 'baptizava',
	'batizando': 'baptizando',
	'bijeção': 'bijecção',
	'batizante': 'baptizante',
	'bissetoes': 'bissectoes',
	'bissoides': 'bissóides',
	'bota de elástica': 'bota-de-elástica',
	'bichos-do-mato': 'b',
	'bidirecional': 'bidireccional',
	'batizemoes': 'baptizemoes',
	'batistérias': 'baptistérias',
	'boca de favas': 'boca-de-favas',
	'bronquetáticas': 'bronquectáticas',
	'braquicataléticas': 'braquicatalécticas',
	'batizassens': 'baptizassens',
	'batizeies': 'baptizeies',
	'batizarans': 'baptizarans',
	'bicho de sete cabeças': 'bicho-de-sete-cabeças',
	'blastoides': 'blastóides',
	'banaboias': 'banabóias',
	'bissetriz': 'bissectriz',
	'boioçuboia': 'boioçubóia',
	'batismal': 'baptismal',
	'belemnoides': 'belemnóides',
	'balão de ensaia': 'balão-de-ensaia',
	'batizoas': 'baptizoas',
	'batizámos': 'baptizámos',
	'batistinos': 'baptistinos',
	'batizarões': 'baptizarões',
	'batizassees': 'baptizassees',
	'batistina': 'baptistina',
	'bilhete de visita': 'bilhete-de-visita',
	'batizarens': 'baptizarens',
	'batizaremoes': 'baptizaremoes',
	'batistino': 'baptistino',
	'batizada': 'baptizada',
	'batistério': 'baptistério',
	'bibliofiláticos': 'bibliofilácticos',
	'batizaria': 'baptizaria',
	'biocoloides': 'biocolóides',
	'batizado': 'baptizado',
	'basiopinacoides': 'basiopinacóides',
	'boias': 'bóias',
	'batizaste': 'baptizaste',
	'batizaráes': 'baptizaráes',
	'batizarâs': 'baptizarâs',
	'birreatoes': 'birreactoes',
	'braços-de-ferro': 'b',
	'batizastees': 'baptizastees',
	'batizais': 'baptizais',
	'barotático': 'barotáctico',
	'barotática': 'barotáctica',
	'boca de foga': 'boca-de-foga',
	'bidirecionais': 'bidireccionais',
	'balanoide': 'balanóide',
	'batismas': 'baptismas',
	'batizarmos': 'baptizarmos',
	'braquicataleto': 'braquicatalecto',
	'batizavans': 'baptizavans',
	'batizarmoes': 'baptizarmoes',
	'beltranas': 'Beltranas',
	'blastoidees': 'blastóidees',
	'boia-fria': 'bóia-fria',
	'batracoides': 'batracóides',
	'batizamentos': 'baptizamentos',
	'biotáticas': 'biotácticas',
	'batismos': 'baptismos',
	'batizáreies': 'baptizáreies',
	'birrefraçâ': 'birrefracçâ',
	'batismo': 'baptismo',
	'batisma': 'baptisma',
	'batizará': 'baptizará',
	'batizarâ': 'baptizarâ',
	'batizasses': 'baptizasses',
	'bibliofilático': 'bibliofiláctico',
	'bico de gavião': 'bico-de-gavião',
	'bibliofilática': 'bibliofiláctica',
	'batizes': 'baptizes',
	'batizem': 'baptizem',
	'biotática': 'biotáctica',
	'birrefraçâs': 'birrefracçâs',
	'basipinacoide': 'basipinacóide',
	'boca de incêndia': 'boca-de-incêndia',
	'biotático': 'biotáctico',
	'batizassem': 'baptizassem',
	'batizavaes': 'baptizavaes',
	'baba de camela': 'baba-de-camela',
	'biobjetiva': 'biobjectiva',
	'bibliofiláticas': 'bibliofilácticas',
	'baba de camelo': 'baba-de-camelo',
	'biobjetivo': 'biobjectivo',
	'batizous': 'baptizous',
	'bioelétrico': 'bioeléctrico',
	'bioelétrica': 'bioeléctrica',
	'batizemos': 'baptizemos',
	'bocas-de-incêndio': 'b',
	'batizamos': 'baptizamos',
	'bioflavonoide': 'bioflavonóide',
	'bioativa': 'bioactiva',
	'batizámoes': 'baptizámoes',
	'bicha de sete cabeças': 'bicha-de-sete-cabeças',
	'bicos-de-gás': 'b',
	'bioativo': 'bioactivo',
	'batizáveies': 'baptizáveies',
	'braquicatalética': 'braquicataléctica',
	'batizaraes': 'baptizaraes',
	'bocas-de-fogo': 'b',
	'batizaríamoes': 'baptizaríamoes',
	'braquicatalético': 'braquicataléctico',
	'batizardees': 'baptizardees',
	'batizaríeies': 'baptizaríeies',
	'batizamoes': 'baptizamoes',
	'bijeções': 'bijecções',
	'boca de fogo': 'boca-de-fogo',
	'botas-de-elástico': 'b',
	'batizaremos': 'baptizaremos',
	'biotáticos': 'biotácticos',
	'batizarei': 'baptizarei',
	'betoias': 'betóias',
	'batizares': 'baptizares',
	'batizávamoes': 'baptizávamoes',
	'batizarees': 'baptizarees',
	'batista': 'baptista',
	'bijeçâs': 'bijecçâs',
	'betoia': 'betóia',
	'bissetries': 'bissectries',
	'batizássemoes': 'baptizássemoes',
	'banaboia': 'banabóia',
	'bola ao cesto': 'bola-ao-cesto',
	'bola ao cesta': 'bola-ao-cesta',
	'batizávamos': 'baptizávamos',
	'biobjetividade': 'biobjectividade',
	'batistinas': 'baptistinas',
	'bioatividades': 'bioactividades',
	'batizaes': 'baptizaes',
	'batizantes': 'baptizantes',
	'batizarás': 'baptizarás',
	'batizai': 'baptizai',
	'batizam': 'baptizam',
	'bicos-de-mocho': 'b',
	'batizar': 'baptizar',
	'batizas': 'baptizas',
	'basiopinacoide': 'basiopinacóide',
	'benzoicos': 'benzóicos',
	'boia': 'bóia',
	'batizariaes': 'baptizariaes',
	'bico de obra': 'bico-de-obra',
	'batizans': 'baptizans',
	'bijeçâ': 'bijecçâ',
	'braquioides': 'braquióides',
	'batismais': 'baptismais',
	'bronquetática': 'bronquectática',
	'botrioides': 'botrióides',
	'barotáticas': 'barotácticas',
	'birreatoras': 'birreactoras',
}